# To use this Docker Compose file for mqttwarn:
#
# 1. Acquire "docker-compose.yml":
# wget https://raw.githubusercontent.com/jpmens/mqttwarn/main/docker-compose.yml
#
# 2. Create a directory for mqttwarn to store "mqttwarn.ini" and "funcs.py" in:
# mkdir /path/to/mqttwarn
#
# 3. Acquire "mqttwarn.ini":
# wget https://raw.githubusercontent.com/jpmens/mqttwarn/main/mqttwarn/examples/basic/mqttwarn.ini -O /path/to/mqtwarn/mqttwarn.ini
#
# 4. Define the location to the custom functions file within "mqttwarn.ini":
#
# functions = 'funcs.py'
version: '3.7'

services:
  mqttwarn:
    image: jpmens/mqttwarn
    container_name: mqttwarn
    restart: always
    volumes:
      - /path/to/mqttwarn:/etc/mqttwarn
      - /etc/localtime:/etc/localtime:ro
    # If you want to change the default location of mqttwarn.ini, uncomment the following lines:
    #environment:
    #  - MQTTWARNINI=/etc/mqttwarn/mqttwarn.ini
